name: Build backend app

on:
  workflow_dispatch:
  push:
    branches:
    - add_actions_backend
    paths:
    - 'backend/**'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  TestAndBuild:
    name: Test and Build backend app
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package package