name: Build backend app

on:
  workflow_dispatch:
  push:
    branches:
    - add_actions_backend
    paths:
    - '.github/workflows/backend.yml'
    - 'backend/**'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  test:
    name: Build backend app and deploy
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Build Backend with Maven
      run: |
        cd backend
        mvn clean package package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: build Backend Dockerfile
      run: |  
        cd backend
        docker build . --tag bootcamp-backend:1.0.0

    - name: list docker image
      run: docker image ls
