name: Build backend app

on:
  workflow_dispatch:
  push:
    branches:
    - add_actions_backend
    paths:
    - '.github/workflows/backend.yml'
    - 'backend/**'

env:
  USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GH_TOKEN2 }}
  REGISTRY: ghcr.io
  IMAGE_NAME: bootcamp-backend
  IMAGE_VERSION: 1.0.1

jobs:
  build_and_push:
    name: Build backend app and deploy
    runs-on: self-hosted
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Test Backend with Maven
      run: |
        cd backend
        mvn clean test

    - name: Build Backend with Maven
      run: |
        cd backend
        mvn clean package

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ env.GH_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Backend Dockerfile
      run: |
        cd backend
        docker build . --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

    - name: Tag Backend Docker image
      run: docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

    - name: Push Backend Docker image
      run:  docker push ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
