name: Build frontend app

defaults:
  run:
    working-directory: "frontend/app"

on:
  workflow_dispatch:
  push:
    branches:
    - add_actions_frontend
    paths:
    - '.github/workflows/frontend-ci.yml'
    - 'frontend/**'

env:
  USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GH_TOKEN2 }}
  REGISTRY: ghcr.io
  IMAGE_NAME: bootcamp-frontend
  IMAGE_VERSION: 1.0.0

jobs:
  build_and_push:
    name: Build backend app and deploy
    runs-on: self-hosted
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Install Angular
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    - name: Run server
      run: npm run start &

    - name: Sleep for 15 seconds
      run: sleep 15s

    - name: Run tests
      run: npm run test

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ env.GH_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Backend Dockerfile
      run: |
        cd ..
        docker build . --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

    - name: Tag Backend Docker image
      run: docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

    - name: Push Backend Docker image
      run:  docker push ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
